FALLBACK_PROBLEMS = {
    "Arrays": [
        {"title": "Two Sum", "leetcode_url": "https://leetcode.com/problems/two-sum/", "difficulty": "Easy"},
        {"title": "Contains Duplicate", "leetcode_url": "https://leetcode.com/problems/contains-duplicate/", "difficulty": "Easy"},
        {"title": "Best Time to Buy and Sell Stock", "leetcode_url": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", "difficulty": "Easy"},
        {"title": "Majority Element", "leetcode_url": "https://leetcode.com/problems/majority-element/", "difficulty": "Easy"},
        {"title": "3Sum", "leetcode_url": "https://leetcode.com/problems/3sum/", "difficulty": "Medium"},
        {"title": "Product of Array Except Self", "leetcode_url": "https://leetcode.com/problems/product-of-array-except-self/", "difficulty": "Medium"},
        {"title": "Subarray Sum Equals K", "leetcode_url": "https://leetcode.com/problems/subarray-sum-equals-k/", "difficulty": "Medium"},
        {"title": "Merge Intervals", "leetcode_url": "https://leetcode.com/problems/merge-intervals/", "difficulty": "Medium"},
        {"title": "First Missing Positive", "leetcode_url": "https://leetcode.com/problems/first-missing-positive/", "difficulty": "Hard"},
        {"title": "Trapping Rain Water", "leetcode_url": "https://leetcode.com/problems/trapping-rain-water/", "difficulty": "Hard"}
    ],
    "Strings": [
        {"title": "Valid Palindrome", "leetcode_url": "https://leetcode.com/problems/valid-palindrome/", "difficulty": "Easy"},
        {"title": "Valid Anagram", "leetcode_url": "https://leetcode.com/problems/valid-anagram/", "difficulty": "Easy"},
        {"title": "Longest Common Prefix", "leetcode_url": "https://leetcode.com/problems/longest-common-prefix/", "difficulty": "Easy"},
        {"title": "Is Subsequence", "leetcode_url": "https://leetcode.com/problems/is-subsequence/", "difficulty": "Easy"},
        {"title": "Longest Substring Without Repeating Characters", "leetcode_url": "https://leetcode.com/problems/longest-substring-without-repeating-characters/", "difficulty": "Medium"},
        {"title": "Group Anagrams", "leetcode_url": "https://leetcode.com/problems/group-anagrams/", "difficulty": "Medium"},
        {"title": "Longest Palindromic Substring", "leetcode_url": "https://leetcode.com/problems/longest-palindromic-substring/", "difficulty": "Medium"},
        {"title": "String to Integer (atoi)", "leetcode_url": "https://leetcode.com/problems/string-to-integer-atoi/", "difficulty": "Medium"},
        {"title": "Minimum Window Substring", "leetcode_url": "https://leetcode.com/problems/minimum-window-substring/", "difficulty": "Hard"},
        {"title": "Regular Expression Matching", "leetcode_url": "https://leetcode.com/problems/regular-expression-matching/", "difficulty": "Hard"}
    ],
    "Hashing": [
        {"title": "Two Sum", "leetcode_url": "https://leetcode.com/problems/two-sum/", "difficulty": "Easy"},
        {"title": "Intersection of Two Arrays", "leetcode_url": "https://leetcode.com/problems/intersection-of-two-arrays/", "difficulty": "Easy"},
        {"title": "Unique Number of Occurrences", "leetcode_url": "https://leetcode.com/problems/unique-number-of-occurrences/", "difficulty": "Easy"},
        {"title": "Path Crossing", "leetcode_url": "https://leetcode.com/problems/path-crossing/", "difficulty": "Easy"},
        {"title": "Group Anagrams", "leetcode_url": "https://leetcode.com/problems/group-anagrams/", "difficulty": "Medium"},
        {"title": "Subarray Sum Equals K", "leetcode_url": "https://leetcode.com/problems/subarray-sum-equals-k/", "difficulty": "Medium"},
        {"title": "Top K Frequent Elements", "leetcode_url": "https://leetcode.com/problems/top-k-frequent-elements/", "difficulty": "Medium"},
        {"title": "Insert Delete GetRandom O(1)", "leetcode_url": "https://leetcode.com/problems/insert-delete-getrandom-o1/", "difficulty": "Medium"},
        {"title": "Max Points on a Line", "leetcode_url": "https://leetcode.com/problems/max-points-on-a-line/", "difficulty": "Hard"},
        {"title": "First Missing Positive", "leetcode_url": "https://leetcode.com/problems/first-missing-positive/", "difficulty": "Hard"}
    ],
    "Two Pointers": [
        {"title": "Valid Palindrome", "leetcode_url": "https://leetcode.com/problems/valid-palindrome/", "difficulty": "Easy"},
        {"title": "Move Zeroes", "leetcode_url": "https://leetcode.com/problems/move-zeroes/", "difficulty": "Easy"},
        {"title": "Merge Sorted Array", "leetcode_url": "https://leetcode.com/problems/merge-sorted-array/", "difficulty": "Easy"},
        {"title": "Remove Duplicates from Sorted Array", "leetcode_url": "https://leetcode.com/problems/remove-duplicates-from-sorted-array/", "difficulty": "Easy"},
        {"title": "3Sum", "leetcode_url": "https://leetcode.com/problems/3sum/", "difficulty": "Medium"},
        {"title": "Container With Most Water", "leetcode_url": "https://leetcode.com/problems/container-with-most-water/", "difficulty": "Medium"},
        {"title": "Two Sum II - Input Array Is Sorted", "leetcode_url": "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/", "difficulty": "Medium"},
        {"title": "3Sum Closest", "leetcode_url": "https://leetcode.com/problems/3sum-closest/", "difficulty": "Medium"},
        {"title": "Trapping Rain Water", "leetcode_url": "https://leetcode.com/problems/trapping-rain-water/", "difficulty": "Hard"},
        {"title": "Valid Number", "leetcode_url": "https://leetcode.com/problems/valid-number/", "difficulty": "Hard"}
    ],
    "Sliding Window": [
        {"title": "Best Time to Buy and Sell Stock", "leetcode_url": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", "difficulty": "Easy"},
        {"title": "Defuse the Bomb", "leetcode_url": "https://leetcode.com/problems/defuse-the-bomb/", "difficulty": "Easy"},
        {"title": "Minimum Difference Between Highest and Lowest of K Scores", "leetcode_url": "https://leetcode.com/problems/minimum-difference-between-highest-and-lowest-of-k-scores/", "difficulty": "Easy"},
        {"title": "Longest Nice Substring", "leetcode_url": "https://leetcode.com/problems/longest-nice-substring/", "difficulty": "Easy"},
        {"title": "Longest Substring Without Repeating Characters", "leetcode_url": "https://leetcode.com/problems/longest-substring-without-repeating-characters/", "difficulty": "Medium"},
        {"title": "Longest Repeating Character Replacement", "leetcode_url": "https://leetcode.com/problems/longest-repeating-character-replacement/", "difficulty": "Medium"},
        {"title": "Permutation in String", "leetcode_url": "https://leetcode.com/problems/permutation-in-string/", "difficulty": "Medium"},
        {"title": "Minimum Size Subarray Sum", "leetcode_url": "https://leetcode.com/problems/minimum-size-subarray-sum/", "difficulty": "Medium"},
        {"title": "Minimum Window Substring", "leetcode_url": "https://leetcode.com/problems/minimum-window-substring/", "difficulty": "Hard"},
        {"title": "Sliding Window Maximum", "leetcode_url": "https://leetcode.com/problems/sliding-window-maximum/", "difficulty": "Hard"}
    ],
    "Binary Search": [
        {"title": "Binary Search", "leetcode_url": "https://leetcode.com/problems/binary-search/", "difficulty": "Easy"},
        {"title": "First Bad Version", "leetcode_url": "https://leetcode.com/problems/first-bad-version/", "difficulty": "Easy"},
        {"title": "Search Insert Position", "leetcode_url": "https://leetcode.com/problems/search-insert-position/", "difficulty": "Easy"},
        {"title": "Guess Number Higher or Lower", "leetcode_url": "https://leetcode.com/problems/guess-number-higher-or-lower/", "difficulty": "Easy"},
        {"title": "Search in Rotated Sorted Array", "leetcode_url": "https://leetcode.com/problems/search-in-rotated-sorted-array/", "difficulty": "Medium"},
        {"title": "Find Minimum in Rotated Sorted Array", "leetcode_url": "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", "difficulty": "Medium"},
        {"title": "Search a 2D Matrix", "leetcode_url": "https://leetcode.com/problems/search-a-2d-matrix/", "difficulty": "Medium"},
        {"title": "Koko Eating Bananas", "leetcode_url": "https://leetcode.com/problems/koko-eating-bananas/", "difficulty": "Medium"},
        {"title": "Median of Two Sorted Arrays", "leetcode_url": "https://leetcode.com/problems/median-of-two-sorted-arrays/", "difficulty": "Hard"},
        {"title": "Split Array Largest Sum", "leetcode_url": "https://leetcode.com/problems/split-array-largest-sum/", "difficulty": "Hard"}
    ],
    "Linked List": [
        {"title": "Reverse Linked List", "leetcode_url": "https://leetcode.com/problems/reverse-linked-list/", "difficulty": "Easy"},
        {"title": "Merge Two Sorted Lists", "leetcode_url": "https://leetcode.com/problems/merge-two-sorted-lists/", "difficulty": "Easy"},
        {"title": "Linked List Cycle", "leetcode_url": "https://leetcode.com/problems/linked-list-cycle/", "difficulty": "Easy"},
        {"title": "Remove Duplicates from Sorted List", "leetcode_url": "https://leetcode.com/problems/remove-duplicates-from-sorted-list/", "difficulty": "Easy"},
        {"title": "Remove Nth Node From End of List", "leetcode_url": "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", "difficulty": "Medium"},
        {"title": "Add Two Numbers", "leetcode_url": "https://leetcode.com/problems/add-two-numbers/", "difficulty": "Medium"},
        {"title": "Copy List with Random Pointer", "leetcode_url": "https://leetcode.com/problems/copy-list-with-random-pointer/", "difficulty": "Medium"},
        {"title": "Reorder List", "leetcode_url": "https://leetcode.com/problems/reorder-list/", "difficulty": "Medium"},
        {"title": "Merge k Sorted Lists", "leetcode_url": "https://leetcode.com/problems/merge-k-sorted-lists/", "difficulty": "Hard"},
        {"title": "Reverse Nodes in k-Group", "leetcode_url": "https://leetcode.com/problems/reverse-nodes-in-k-group/", "difficulty": "Hard"}
    ],
    "Stack": [
        {"title": "Valid Parentheses", "leetcode_url": "https://leetcode.com/problems/valid-parentheses/", "difficulty": "Easy"},
        {"title": "Min Stack", "leetcode_url": "https://leetcode.com/problems/min-stack/", "difficulty": "Easy"},
        {"title": "Implement Queue using Stacks", "leetcode_url": "https://leetcode.com/problems/implement-queue-using-stacks/", "difficulty": "Easy"},
        {"title": "Make The String Great", "leetcode_url": "https://leetcode.com/problems/make-the-string-great/", "difficulty": "Easy"},
        {"title": "Evaluate Reverse Polish Notation", "leetcode_url": "https://leetcode.com/problems/evaluate-reverse-polish-notation/", "difficulty": "Medium"},
        {"title": "Daily Temperatures", "leetcode_url": "https://leetcode.com/problems/daily-temperatures/", "difficulty": "Medium"},
        {"title": "Generate Parentheses", "leetcode_url": "https://leetcode.com/problems/generate-parentheses/", "difficulty": "Medium"},
        {"title": "Car Fleet", "leetcode_url": "https://leetcode.com/problems/car-fleet/", "difficulty": "Medium"},
        {"title": "Largest Rectangle in Histogram", "leetcode_url": "https://leetcode.com/problems/largest-rectangle-in-histogram/", "difficulty": "Hard"},
        {"title": "Maximal Rectangle", "leetcode_url": "https://leetcode.com/problems/maximal-rectangle/", "difficulty": "Hard"}
    ],
    "Trees": [
        {"title": "Maximum Depth of Binary Tree", "leetcode_url": "https://leetcode.com/problems/maximum-depth-of-binary-tree/", "difficulty": "Easy"},
        {"title": "Same Tree", "leetcode_url": "https://leetcode.com/problems/same-tree/", "difficulty": "Easy"},
        {"title": "Invert Binary Tree", "leetcode_url": "https://leetcode.com/problems/invert-binary-tree/", "difficulty": "Easy"},
        {"title": "Symmetric Tree", "leetcode_url": "https://leetcode.com/problems/symmetric-tree/", "difficulty": "Easy"},
        {"title": "Binary Tree Level Order Traversal", "leetcode_url": "https://leetcode.com/problems/binary-tree-level-order-traversal/", "difficulty": "Medium"},
        {"title": "Binary Tree Right Side View", "leetcode_url": "https://leetcode.com/problems/binary-tree-right-side-view/", "difficulty": "Medium"},
        {"title": "Construct Binary Tree from Preorder and Inorder Traversal", "leetcode_url": "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", "difficulty": "Medium"},
        {"title": "Path Sum III", "leetcode_url": "https://leetcode.com/problems/path-sum-iii/", "difficulty": "Medium"},
        {"title": "Binary Tree Maximum Path Sum", "leetcode_url": "https://leetcode.com/problems/binary-tree-maximum-path-sum/", "difficulty": "Hard"},
        {"title": "Serialize and Deserialize Binary Tree", "leetcode_url": "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", "difficulty": "Hard"}
    ],
    "BST": [
        {"title": "Search in a Binary Search Tree", "leetcode_url": "https://leetcode.com/problems/search-in-a-binary-search-tree/", "difficulty": "Easy"},
        {"title": "Range Sum of BST", "leetcode_url": "https://leetcode.com/problems/range-sum-of-bst/", "difficulty": "Easy"},
        {"title": "Minimum Distance Between BST Nodes", "leetcode_url": "https://leetcode.com/problems/minimum-distance-between-bst-nodes/", "difficulty": "Easy"},
        {"title": "Convert Sorted Array to Binary Search Tree", "leetcode_url": "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/", "difficulty": "Easy"},
        {"title": "Validate Binary Search Tree", "leetcode_url": "https://leetcode.com/problems/validate-binary-search-tree/", "difficulty": "Medium"},
        {"title": "Kth Smallest Element in a BST", "leetcode_url": "https://leetcode.com/problems/kth-smallest-element-in-a-bst/", "difficulty": "Medium"},
        {"title": "Delete Node in a BST", "leetcode_url": "https://leetcode.com/problems/delete-node-in-a-bst/", "difficulty": "Medium"},
        {"title": "Insert into a Binary Search Tree", "leetcode_url": "https://leetcode.com/problems/insert-into-a-binary-search-tree/", "difficulty": "Medium"},
        {"title": "Recover Binary Search Tree", "leetcode_url": "https://leetcode.com/problems/recover-binary-search-tree/", "difficulty": "Hard"},
        {"title": "Number of Ways to Reorder Array to Get Same BST", "leetcode_url": "https://leetcode.com/problems/number-of-ways-to-reorder-array-to-get-same-bst/", "difficulty": "Hard"}
    ],
    "Queue": [
        {"title": "Number of Recent Calls", "leetcode_url": "https://leetcode.com/problems/number-of-recent-calls/", "difficulty": "Easy"},
        {"title": "Implement Stack using Queues", "leetcode_url": "https://leetcode.com/problems/implement-stack-using-queues/", "difficulty": "Easy"},
        {"title": "First Unique Character in a String", "leetcode_url": "https://leetcode.com/problems/first-unique-character-in-a-string/", "difficulty": "Easy"},
        {"title": "Time Needed to Buy Tickets", "leetcode_url": "https://leetcode.com/problems/time-needed-to-buy-tickets/", "difficulty": "Easy"},
        {"title": "Design Circular Queue", "leetcode_url": "https://leetcode.com/problems/design-circular-queue/", "difficulty": "Medium"},
        {"title": "Design Front Middle Back Queue", "leetcode_url": "https://leetcode.com/problems/design-front-middle-back-queue/", "difficulty": "Medium"},
        {"title": "Reveal Cards In Increasing Order", "leetcode_url": "https://leetcode.com/problems/reveal-cards-in-increasing-order/", "difficulty": "Medium"},
        {"title": "Task Scheduler", "leetcode_url": "https://leetcode.com/problems/task-scheduler/", "difficulty": "Medium"},
        {"title": "Shortest Subarray with Sum at Least K", "leetcode_url": "https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/", "difficulty": "Hard"},
        {"title": "Max Value of Equation", "leetcode_url": "https://leetcode.com/problems/max-value-of-equation/", "difficulty": "Hard"}
    ],
    "Heap": [
        {"title": "Last Stone Weight", "leetcode_url": "https://leetcode.com/problems/last-stone-weight/", "difficulty": "Easy"},
        {"title": "Kth Largest Element in a Stream", "leetcode_url": "https://leetcode.com/problems/kth-largest-element-in-a-stream/", "difficulty": "Easy"},
        {"title": "Relative Ranks", "leetcode_url": "https://leetcode.com/problems/relative-ranks/", "difficulty": "Easy"},
        {"title": "Make Array Zero by Subtracting Equal Amounts", "leetcode_url": "https://leetcode.com/problems/make-array-zero-by-subtracting-equal-amounts/", "difficulty": "Easy"},
        {"title": "Kth Largest Element in an Array", "leetcode_url": "https://leetcode.com/problems/kth-largest-element-in-an-array/", "difficulty": "Medium"},
        {"title": "Top K Frequent Elements", "leetcode_url": "https://leetcode.com/problems/top-k-frequent-elements/", "difficulty": "Medium"},
        {"title": "Find K Closest Elements", "leetcode_url": "https://leetcode.com/problems/find-k-closest-elements/", "difficulty": "Medium"},
        {"title": "K Closest Points to Origin", "leetcode_url": "https://leetcode.com/problems/k-closest-points-to-origin/", "difficulty": "Medium"},
        {"title": "Find Median from Data Stream", "leetcode_url": "https://leetcode.com/problems/find-median-from-data-stream/", "difficulty": "Hard"},
        {"title": "Merge k Sorted Lists", "leetcode_url": "https://leetcode.com/problems/merge-k-sorted-lists/", "difficulty": "Hard"}
    ],
    "Graphs": [
        {"title": "Find Center of Star Graph", "leetcode_url": "https://leetcode.com/problems/find-center-of-star-graph/", "difficulty": "Easy"},
        {"title": "Find Town Judge", "leetcode_url": "https://leetcode.com/problems/find-town-judge/", "difficulty": "Easy"},
        {"title": "Island Perimeter", "leetcode_url": "https://leetcode.com/problems/island-perimeter/", "difficulty": "Easy"},
        {"title": "Flood Fill", "leetcode_url": "https://leetcode.com/problems/flood-fill/", "difficulty": "Easy"},
        {"title": "Clone Graph", "leetcode_url": "https://leetcode.com/problems/clone-graph/", "difficulty": "Medium"},
        {"title": "Course Schedule", "leetcode_url": "https://leetcode.com/problems/course-schedule/", "difficulty": "Medium"},
        {"title": "Number of Islands", "leetcode_url": "https://leetcode.com/problems/number-of-islands/", "difficulty": "Medium"},
        {"title": "Rotting Oranges", "leetcode_url": "https://leetcode.com/problems/rotting-oranges/", "difficulty": "Medium"},
        {"title": "Word Ladder", "leetcode_url": "https://leetcode.com/problems/word-ladder/", "difficulty": "Hard"},
        {"title": "Longest Increasing Path in a Matrix", "leetcode_url": "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/", "difficulty": "Hard"}
    ],
    "Backtracking": [
        {"title": "Binary Watch", "leetcode_url": "https://leetcode.com/problems/binary-watch/", "difficulty": "Easy"},
        {"title": "Sum of All Subset XOR Totals", "leetcode_url": "https://leetcode.com/problems/sum-of-all-subset-xor-totals/", "difficulty": "Easy"},
        {"title": "Binary Tree Paths", "leetcode_url": "https://leetcode.com/problems/binary-tree-paths/", "difficulty": "Easy"},
        {"title": "Flood Fill", "leetcode_url": "https://leetcode.com/problems/flood-fill/", "difficulty": "Easy"},
        {"title": "Subsets", "leetcode_url": "https://leetcode.com/problems/subsets/", "difficulty": "Medium"},
        {"title": "Permutations", "leetcode_url": "https://leetcode.com/problems/permutations/", "difficulty": "Medium"},
        {"title": "Combination Sum", "leetcode_url": "https://leetcode.com/problems/combination-sum/", "difficulty": "Medium"},
        {"title": "Word Search", "leetcode_url": "https://leetcode.com/problems/word-search/", "difficulty": "Medium"},
        {"title": "N-Queens", "leetcode_url": "https://leetcode.com/problems/n-queens/", "difficulty": "Hard"},
        {"title": "Sudoku Solver", "leetcode_url": "https://leetcode.com/problems/sudoku-solver/", "difficulty": "Hard"}
    ],
    "Dynamic Prog.": [
        {"title": "Climbing Stairs", "leetcode_url": "https://leetcode.com/problems/climbing-stairs/", "difficulty": "Easy"},
        {"title": "Min Cost Climbing Stairs", "leetcode_url": "https://leetcode.com/problems/min-cost-climbing-stairs/", "difficulty": "Easy"},
        {"title": "Fibonacci Number", "leetcode_url": "https://leetcode.com/problems/fibonacci-number/", "difficulty": "Easy"},
        {"title": "N-th Tribonacci Number", "leetcode_url": "https://leetcode.com/problems/n-th-tribonacci-number/", "difficulty": "Easy"},
        {"title": "House Robber", "leetcode_url": "https://leetcode.com/problems/house-robber/", "difficulty": "Medium"},
        {"title": "Longest Increasing Subsequence", "leetcode_url": "https://leetcode.com/problems/longest-increasing-subsequence/", "difficulty": "Medium"},
        {"title": "Coin Change", "leetcode_url": "https://leetcode.com/problems/coin-change/", "difficulty": "Medium"},
        {"title": "Unique Paths", "leetcode_url": "https://leetcode.com/problems/unique-paths/", "difficulty": "Medium"},
        {"title": "Edit Distance", "leetcode_url": "https://leetcode.com/problems/edit-distance/", "difficulty": "Hard"},
        {"title": "Longest Valid Parentheses", "leetcode_url": "https://leetcode.com/problems/longest-valid-parentheses/", "difficulty": "Hard"}
    ],
    "Tries": [
        {"title": "Implement Trie (Prefix Tree)", "leetcode_url": "https://leetcode.com/problems/implement-trie-prefix-tree/", "difficulty": "Easy"},
        {"title": "Longest Common Prefix", "leetcode_url": "https://leetcode.com/problems/longest-common-prefix/", "difficulty": "Easy"},
        {"title": "Map Sum Pairs", "leetcode_url": "https://leetcode.com/problems/map-sum-pairs/", "difficulty": "Easy"},
        {"title": "Replace Words", "leetcode_url": "https://leetcode.com/problems/replace-words/", "difficulty": "Easy"},
        {"title": "Design Add and Search Words Data Structure", "leetcode_url": "https://leetcode.com/problems/design-add-and-search-words-data-structure/", "difficulty": "Medium"},
        {"title": "Search Suggestions System", "leetcode_url": "https://leetcode.com/problems/search-suggestions-system/", "difficulty": "Medium"},
        {"title": "Extra Character in a String", "leetcode_url": "https://leetcode.com/problems/extra-character-in-a-string/", "difficulty": "Medium"},
        {"title": "Lexicographical Numbers", "leetcode_url": "https://leetcode.com/problems/lexicographical-numbers/", "difficulty": "Medium"},
        {"title": "Word Search II", "leetcode_url": "https://leetcode.com/problems/word-search-ii/", "difficulty": "Hard"},
        {"title": "Stream of Characters", "leetcode_url": "https://leetcode.com/problems/stream-of-characters/", "difficulty": "Hard"}
    ]
}
