"""NeetCode 150 Problems List"""

NEETCODE_150 = {
    "Arrays & Hashing": [
        {"title": 'Contains Duplicate', "leetcode_url": 'https://leetcode.com/problems/contains-duplicate/', "difficulty": 'Easy'},
        {"title": 'Valid Anagram', "leetcode_url": 'https://leetcode.com/problems/valid-anagram/', "difficulty": 'Easy'},
        {"title": 'Two Sum', "leetcode_url": 'https://leetcode.com/problems/two-sum/', "difficulty": 'Easy'},
        {"title": 'Group Anagrams', "leetcode_url": 'https://leetcode.com/problems/group-anagrams/', "difficulty": 'Medium'},
        {"title": 'Top K Frequent Elements', "leetcode_url": 'https://leetcode.com/problems/top-k-frequent-elements/', "difficulty": 'Medium'},
        {"title": 'Encode and Decode Strings', "leetcode_url": 'https://leetcode.com/problems/encode-and-decode-strings/', "difficulty": 'Medium'},
        {"title": 'Product of Array Except Self', "leetcode_url": 'https://leetcode.com/problems/product-of-array-except-self/', "difficulty": 'Medium'},
        {"title": 'Valid Sudoku', "leetcode_url": 'https://leetcode.com/problems/valid-sudoku/', "difficulty": 'Medium'},
        {"title": 'Longest Consecutive Sequence', "leetcode_url": 'https://leetcode.com/problems/longest-consecutive-sequence/', "difficulty": 'Medium'},
    ],
    "Two Pointers": [
        {"title": 'Valid Palindrome', "leetcode_url": 'https://leetcode.com/problems/valid-palindrome/', "difficulty": 'Easy'},
        {"title": 'Two Sum II Input Array Is Sorted', "leetcode_url": 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/', "difficulty": 'Medium'},
        {"title": '3Sum', "leetcode_url": 'https://leetcode.com/problems/3sum/', "difficulty": 'Medium'},
        {"title": 'Container With Most Water', "leetcode_url": 'https://leetcode.com/problems/container-with-most-water/', "difficulty": 'Medium'},
        {"title": 'Trapping Rain Water', "leetcode_url": 'https://leetcode.com/problems/trapping-rain-water/', "difficulty": 'Hard'},
    ],
    "Sliding Window": [
        {"title": 'Best Time to Buy And Sell Stock', "leetcode_url": 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', "difficulty": 'Easy'},
        {"title": 'Longest Substring Without Repeating Characters', "leetcode_url": 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', "difficulty": 'Medium'},
        {"title": 'Longest Repeating Character Replacement', "leetcode_url": 'https://leetcode.com/problems/longest-repeating-character-replacement/', "difficulty": 'Medium'},
        {"title": 'Permutation In String', "leetcode_url": 'https://leetcode.com/problems/permutation-in-string/', "difficulty": 'Medium'},
        {"title": 'Minimum Window Substring', "leetcode_url": 'https://leetcode.com/problems/minimum-window-substring/', "difficulty": 'Hard'},
        {"title": 'Sliding Window Maximum', "leetcode_url": 'https://leetcode.com/problems/sliding-window-maximum/', "difficulty": 'Hard'},
    ],
    "Stack": [
        {"title": 'Valid Parentheses', "leetcode_url": 'https://leetcode.com/problems/valid-parentheses/', "difficulty": 'Easy'},
        {"title": 'Min Stack', "leetcode_url": 'https://leetcode.com/problems/min-stack/', "difficulty": 'Medium'},
        {"title": 'Evaluate Reverse Polish Notation', "leetcode_url": 'https://leetcode.com/problems/evaluate-reverse-polish-notation/', "difficulty": 'Medium'},
        {"title": 'Daily Temperatures', "leetcode_url": 'https://leetcode.com/problems/daily-temperatures/', "difficulty": 'Medium'},
        {"title": 'Car Fleet', "leetcode_url": 'https://leetcode.com/problems/car-fleet/', "difficulty": 'Medium'},
        {"title": 'Largest Rectangle In Histogram', "leetcode_url": 'https://leetcode.com/problems/largest-rectangle-in-histogram/', "difficulty": 'Hard'},
    ],
    "Binary Search": [
        {"title": 'Binary Search', "leetcode_url": 'https://leetcode.com/problems/binary-search/', "difficulty": 'Easy'},
        {"title": 'Search a 2D Matrix', "leetcode_url": 'https://leetcode.com/problems/search-a-2d-matrix/', "difficulty": 'Medium'},
        {"title": 'Koko Eating Bananas', "leetcode_url": 'https://leetcode.com/problems/koko-eating-bananas/', "difficulty": 'Medium'},
        {"title": 'Find Minimum In Rotated Sorted Array', "leetcode_url": 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/', "difficulty": 'Medium'},
        {"title": 'Search In Rotated Sorted Array', "leetcode_url": 'https://leetcode.com/problems/search-in-rotated-sorted-array/', "difficulty": 'Medium'},
        {"title": 'Time Based Key Value Store', "leetcode_url": 'https://leetcode.com/problems/time-based-key-value-store/', "difficulty": 'Medium'},
        {"title": 'Median of Two Sorted Arrays', "leetcode_url": 'https://leetcode.com/problems/median-of-two-sorted-arrays/', "difficulty": 'Hard'},
    ],
    "Linked List": [
        {"title": 'Reverse Linked List', "leetcode_url": 'https://leetcode.com/problems/reverse-linked-list/', "difficulty": 'Easy'},
        {"title": 'Merge Two Sorted Lists', "leetcode_url": 'https://leetcode.com/problems/merge-two-sorted-lists/', "difficulty": 'Easy'},
        {"title": 'Linked List Cycle', "leetcode_url": 'https://leetcode.com/problems/linked-list-cycle/', "difficulty": 'Easy'},
        {"title": 'Reorder List', "leetcode_url": 'https://leetcode.com/problems/reorder-list/', "difficulty": 'Medium'},
        {"title": 'Remove Nth Node From End of List', "leetcode_url": 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/', "difficulty": 'Medium'},
        {"title": 'Copy List With Random Pointer', "leetcode_url": 'https://leetcode.com/problems/copy-list-with-random-pointer/', "difficulty": 'Medium'},
        {"title": 'Add Two Numbers', "leetcode_url": 'https://leetcode.com/problems/add-two-numbers/', "difficulty": 'Medium'},
        {"title": 'Find The Duplicate Number', "leetcode_url": 'https://leetcode.com/problems/find-the-duplicate-number/', "difficulty": 'Medium'},
        {"title": 'LRU Cache', "leetcode_url": 'https://leetcode.com/problems/lru-cache/', "difficulty": 'Medium'},
        {"title": 'Merge K Sorted Lists', "leetcode_url": 'https://leetcode.com/problems/merge-k-sorted-lists/', "difficulty": 'Hard'},
        {"title": 'Reverse Nodes In K Group', "leetcode_url": 'https://leetcode.com/problems/reverse-nodes-in-k-group/', "difficulty": 'Hard'},
    ],
    "Trees": [
        {"title": 'Invert Binary Tree', "leetcode_url": 'https://leetcode.com/problems/invert-binary-tree/', "difficulty": 'Easy'},
        {"title": 'Maximum Depth of Binary Tree', "leetcode_url": 'https://leetcode.com/problems/maximum-depth-of-binary-tree/', "difficulty": 'Easy'},
        {"title": 'Diameter of Binary Tree', "leetcode_url": 'https://leetcode.com/problems/diameter-of-binary-tree/', "difficulty": 'Easy'},
        {"title": 'Balanced Binary Tree', "leetcode_url": 'https://leetcode.com/problems/balanced-binary-tree/', "difficulty": 'Easy'},
        {"title": 'Same Tree', "leetcode_url": 'https://leetcode.com/problems/same-tree/', "difficulty": 'Easy'},
        {"title": 'Subtree of Another Tree', "leetcode_url": 'https://leetcode.com/problems/subtree-of-another-tree/', "difficulty": 'Easy'},
        {"title": 'Lowest Common Ancestor of a Binary Search Tree', "leetcode_url": 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/', "difficulty": 'Medium'},
        {"title": 'Binary Tree Level Order Traversal', "leetcode_url": 'https://leetcode.com/problems/binary-tree-level-order-traversal/', "difficulty": 'Medium'},
        {"title": 'Binary Tree Right Side View', "leetcode_url": 'https://leetcode.com/problems/binary-tree-right-side-view/', "difficulty": 'Medium'},
        {"title": 'Count Good Nodes In Binary Tree', "leetcode_url": 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/', "difficulty": 'Medium'},
        {"title": 'Validate Binary Search Tree', "leetcode_url": 'https://leetcode.com/problems/validate-binary-search-tree/', "difficulty": 'Medium'},
        {"title": 'Kth Smallest Element In a Bst', "leetcode_url": 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/', "difficulty": 'Medium'},
        {"title": 'Construct Binary Tree From Preorder And Inorder Traversal', "leetcode_url": 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/', "difficulty": 'Medium'},
        {"title": 'Binary Tree Maximum Path Sum', "leetcode_url": 'https://leetcode.com/problems/binary-tree-maximum-path-sum/', "difficulty": 'Hard'},
        {"title": 'Serialize And Deserialize Binary Tree', "leetcode_url": 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/', "difficulty": 'Hard'},
    ],
    "Heap / Priority Queue": [
        {"title": 'Kth Largest Element In a Stream', "leetcode_url": 'https://leetcode.com/problems/kth-largest-element-in-a-stream/', "difficulty": 'Easy'},
        {"title": 'Last Stone Weight', "leetcode_url": 'https://leetcode.com/problems/last-stone-weight/', "difficulty": 'Easy'},
        {"title": 'K Closest Points to Origin', "leetcode_url": 'https://leetcode.com/problems/k-closest-points-to-origin/', "difficulty": 'Medium'},
        {"title": 'Kth Largest Element In An Array', "leetcode_url": 'https://leetcode.com/problems/kth-largest-element-in-an-array/', "difficulty": 'Medium'},
        {"title": 'Task Scheduler', "leetcode_url": 'https://leetcode.com/problems/task-scheduler/', "difficulty": 'Medium'},
        {"title": 'Design Twitter', "leetcode_url": 'https://leetcode.com/problems/design-twitter/', "difficulty": 'Medium'},
        {"title": 'Find Median From Data Stream', "leetcode_url": 'https://leetcode.com/problems/find-median-from-data-stream/', "difficulty": 'Hard'},
    ],
    "Backtracking": [
        {"title": 'Subsets', "leetcode_url": 'https://leetcode.com/problems/subsets/', "difficulty": 'Medium'},
        {"title": 'Combination Sum', "leetcode_url": 'https://leetcode.com/problems/combination-sum/', "difficulty": 'Medium'},
        {"title": 'Combination Sum II', "leetcode_url": 'https://leetcode.com/problems/combination-sum-ii/', "difficulty": 'Medium'},
        {"title": 'Permutations', "leetcode_url": 'https://leetcode.com/problems/permutations/', "difficulty": 'Medium'},
        {"title": 'Subsets II', "leetcode_url": 'https://leetcode.com/problems/subsets-ii/', "difficulty": 'Medium'},
        {"title": 'Generate Parentheses', "leetcode_url": 'https://leetcode.com/problems/generate-parentheses/', "difficulty": 'Medium'},
        {"title": 'Word Search', "leetcode_url": 'https://leetcode.com/problems/word-search/', "difficulty": 'Medium'},
        {"title": 'Palindrome Partitioning', "leetcode_url": 'https://leetcode.com/problems/palindrome-partitioning/', "difficulty": 'Medium'},
        {"title": 'Letter Combinations of a Phone Number', "leetcode_url": 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/', "difficulty": 'Medium'},
        {"title": 'N Queens', "leetcode_url": 'https://leetcode.com/problems/n-queens/', "difficulty": 'Hard'},
    ],
    "Tries": [
        {"title": 'Implement Trie Prefix Tree', "leetcode_url": 'https://leetcode.com/problems/implement-trie-prefix-tree/', "difficulty": 'Medium'},
        {"title": 'Design Add And Search Words Data Structure', "leetcode_url": 'https://leetcode.com/problems/design-add-and-search-words-data-structure/', "difficulty": 'Medium'},
        {"title": 'Word Search II', "leetcode_url": 'https://leetcode.com/problems/word-search-ii/', "difficulty": 'Hard'},
    ],
    "Graphs": [
        {"title": 'Number of Islands', "leetcode_url": 'https://leetcode.com/problems/number-of-islands/', "difficulty": 'Medium'},
        {"title": 'Max Area of Island', "leetcode_url": 'https://leetcode.com/problems/max-area-of-island/', "difficulty": 'Medium'},
        {"title": 'Clone Graph', "leetcode_url": 'https://leetcode.com/problems/clone-graph/', "difficulty": 'Medium'},
        {"title": 'Walls And Gates', "leetcode_url": 'https://leetcode.com/problems/walls-and-gates/', "difficulty": 'Medium'},
        {"title": 'Rotting Oranges', "leetcode_url": 'https://leetcode.com/problems/rotting-oranges/', "difficulty": 'Medium'},
        {"title": 'Pacific Atlantic Water Flow', "leetcode_url": 'https://leetcode.com/problems/pacific-atlantic-water-flow/', "difficulty": 'Medium'},
        {"title": 'Surrounded Regions', "leetcode_url": 'https://leetcode.com/problems/surrounded-regions/', "difficulty": 'Medium'},
        {"title": 'Course Schedule', "leetcode_url": 'https://leetcode.com/problems/course-schedule/', "difficulty": 'Medium'},
        {"title": 'Course Schedule II', "leetcode_url": 'https://leetcode.com/problems/course-schedule-ii/', "difficulty": 'Medium'},
        {"title": 'Graph Valid Tree', "leetcode_url": 'https://leetcode.com/problems/graph-valid-tree/', "difficulty": 'Medium'},
        {"title": 'Number of Connected Components In An Undirected Graph', "leetcode_url": 'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/', "difficulty": 'Medium'},
        {"title": 'Redundant Connection', "leetcode_url": 'https://leetcode.com/problems/redundant-connection/', "difficulty": 'Medium'},
        {"title": 'Word Ladder', "leetcode_url": 'https://leetcode.com/problems/word-ladder/', "difficulty": 'Hard'},
    ],
    "Advanced Graphs": [
        {"title": 'Network Delay Time', "leetcode_url": 'https://leetcode.com/problems/network-delay-time/', "difficulty": 'Medium'},
        {"title": 'Reconstruct Itinerary', "leetcode_url": 'https://leetcode.com/problems/reconstruct-itinerary/', "difficulty": 'Hard'},
        {"title": 'Min Cost to Connect All Points', "leetcode_url": 'https://leetcode.com/problems/min-cost-to-connect-all-points/', "difficulty": 'Medium'},
        {"title": 'Swim In Rising Water', "leetcode_url": 'https://leetcode.com/problems/swim-in-rising-water/', "difficulty": 'Hard'},
        {"title": 'Alien Dictionary', "leetcode_url": 'https://leetcode.com/problems/alien-dictionary/', "difficulty": 'Hard'},
        {"title": 'Cheapest Flights Within K Stops', "leetcode_url": 'https://leetcode.com/problems/cheapest-flights-within-k-stops/', "difficulty": 'Medium'},
    ],
    "1-D Dynamic Programming": [
        {"title": 'Climbing Stairs', "leetcode_url": 'https://leetcode.com/problems/climbing-stairs/', "difficulty": 'Easy'},
        {"title": 'Min Cost Climbing Stairs', "leetcode_url": 'https://leetcode.com/problems/min-cost-climbing-stairs/', "difficulty": 'Easy'},
        {"title": 'House Robber', "leetcode_url": 'https://leetcode.com/problems/house-robber/', "difficulty": 'Medium'},
        {"title": 'House Robber II', "leetcode_url": 'https://leetcode.com/problems/house-robber-ii/', "difficulty": 'Medium'},
        {"title": 'Longest Palindromic Substring', "leetcode_url": 'https://leetcode.com/problems/longest-palindromic-substring/', "difficulty": 'Medium'},
        {"title": 'Palindromic Substrings', "leetcode_url": 'https://leetcode.com/problems/palindromic-substrings/', "difficulty": 'Medium'},
        {"title": 'Decode Ways', "leetcode_url": 'https://leetcode.com/problems/decode-ways/', "difficulty": 'Medium'},
        {"title": 'Coin Change', "leetcode_url": 'https://leetcode.com/problems/coin-change/', "difficulty": 'Medium'},
        {"title": 'Maximum Product Subarray', "leetcode_url": 'https://leetcode.com/problems/maximum-product-subarray/', "difficulty": 'Medium'},
        {"title": 'Word Break', "leetcode_url": 'https://leetcode.com/problems/word-break/', "difficulty": 'Medium'},
        {"title": 'Longest Increasing Subsequence', "leetcode_url": 'https://leetcode.com/problems/longest-increasing-subsequence/', "difficulty": 'Medium'},
        {"title": 'Partition Equal Subset Sum', "leetcode_url": 'https://leetcode.com/problems/partition-equal-subset-sum/', "difficulty": 'Medium'},
    ],
    "2-D Dynamic Programming": [
        {"title": 'Unique Paths', "leetcode_url": 'https://leetcode.com/problems/unique-paths/', "difficulty": 'Medium'},
        {"title": 'Longest Common Subsequence', "leetcode_url": 'https://leetcode.com/problems/longest-common-subsequence/', "difficulty": 'Medium'},
        {"title": 'Best Time to Buy And Sell Stock With Cooldown', "leetcode_url": 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/', "difficulty": 'Medium'},
        {"title": 'Coin Change II', "leetcode_url": 'https://leetcode.com/problems/coin-change-ii/', "difficulty": 'Medium'},
        {"title": 'Target Sum', "leetcode_url": 'https://leetcode.com/problems/target-sum/', "difficulty": 'Medium'},
        {"title": 'Interleaving String', "leetcode_url": 'https://leetcode.com/problems/interleaving-string/', "difficulty": 'Medium'},
        {"title": 'Longest Increasing Path In a Matrix', "leetcode_url": 'https://leetcode.com/problems/longest-increasing-path-in-a-matrix/', "difficulty": 'Hard'},
        {"title": 'Distinct Subsequences', "leetcode_url": 'https://leetcode.com/problems/distinct-subsequences/', "difficulty": 'Hard'},
        {"title": 'Edit Distance', "leetcode_url": 'https://leetcode.com/problems/edit-distance/', "difficulty": 'Medium'},
        {"title": 'Burst Balloons', "leetcode_url": 'https://leetcode.com/problems/burst-balloons/', "difficulty": 'Hard'},
        {"title": 'Regular Expression Matching', "leetcode_url": 'https://leetcode.com/problems/regular-expression-matching/', "difficulty": 'Hard'},
    ],
    "Greedy": [
        {"title": 'Maximum Subarray', "leetcode_url": 'https://leetcode.com/problems/maximum-subarray/', "difficulty": 'Medium'},
        {"title": 'Jump Game', "leetcode_url": 'https://leetcode.com/problems/jump-game/', "difficulty": 'Medium'},
        {"title": 'Jump Game II', "leetcode_url": 'https://leetcode.com/problems/jump-game-ii/', "difficulty": 'Medium'},
        {"title": 'Gas Station', "leetcode_url": 'https://leetcode.com/problems/gas-station/', "difficulty": 'Medium'},
        {"title": 'Hand of Straights', "leetcode_url": 'https://leetcode.com/problems/hand-of-straights/', "difficulty": 'Medium'},
        {"title": 'Merge Triplets to Form Target Triplet', "leetcode_url": 'https://leetcode.com/problems/merge-triplets-to-form-target-triplet/', "difficulty": 'Medium'},
        {"title": 'Partition Labels', "leetcode_url": 'https://leetcode.com/problems/partition-labels/', "difficulty": 'Medium'},
        {"title": 'Valid Parenthesis String', "leetcode_url": 'https://leetcode.com/problems/valid-parenthesis-string/', "difficulty": 'Medium'},
    ],
    "Intervals": [
        {"title": 'Insert Interval', "leetcode_url": 'https://leetcode.com/problems/insert-interval/', "difficulty": 'Medium'},
        {"title": 'Merge Intervals', "leetcode_url": 'https://leetcode.com/problems/merge-intervals/', "difficulty": 'Medium'},
        {"title": 'Non Overlapping Intervals', "leetcode_url": 'https://leetcode.com/problems/non-overlapping-intervals/', "difficulty": 'Medium'},
        {"title": 'Meeting Rooms', "leetcode_url": 'https://leetcode.com/problems/meeting-rooms/', "difficulty": 'Easy'},
        {"title": 'Meeting Rooms II', "leetcode_url": 'https://leetcode.com/problems/meeting-rooms-ii/', "difficulty": 'Medium'},
        {"title": 'Minimum Interval to Include Each Query', "leetcode_url": 'https://leetcode.com/problems/minimum-interval-to-include-each-query/', "difficulty": 'Hard'},
    ],
    "Math & Geometry": [
        {"title": 'Rotate Image', "leetcode_url": 'https://leetcode.com/problems/rotate-image/', "difficulty": 'Medium'},
        {"title": 'Spiral Matrix', "leetcode_url": 'https://leetcode.com/problems/spiral-matrix/', "difficulty": 'Medium'},
        {"title": 'Set Matrix Zeroes', "leetcode_url": 'https://leetcode.com/problems/set-matrix-zeroes/', "difficulty": 'Medium'},
        {"title": 'Happy Number', "leetcode_url": 'https://leetcode.com/problems/happy-number/', "difficulty": 'Easy'},
        {"title": 'Plus One', "leetcode_url": 'https://leetcode.com/problems/plus-one/', "difficulty": 'Easy'},
        {"title": 'Pow(x, n)', "leetcode_url": 'https://leetcode.com/problems/powx-n/', "difficulty": 'Medium'},
        {"title": 'Multiply Strings', "leetcode_url": 'https://leetcode.com/problems/multiply-strings/', "difficulty": 'Medium'},
        {"title": 'Detect Squares', "leetcode_url": 'https://leetcode.com/problems/detect-squares/', "difficulty": 'Medium'},
    ],
    "Bit Manipulation": [
        {"title": 'Single Number', "leetcode_url": 'https://leetcode.com/problems/single-number/', "difficulty": 'Easy'},
        {"title": 'Number of 1 Bits', "leetcode_url": 'https://leetcode.com/problems/number-of-1-bits/', "difficulty": 'Easy'},
        {"title": 'Counting Bits', "leetcode_url": 'https://leetcode.com/problems/counting-bits/', "difficulty": 'Easy'},
        {"title": 'Reverse Bits', "leetcode_url": 'https://leetcode.com/problems/reverse-bits/', "difficulty": 'Easy'},
        {"title": 'Missing Number', "leetcode_url": 'https://leetcode.com/problems/missing-number/', "difficulty": 'Easy'},
        {"title": 'Sum of Two Integers', "leetcode_url": 'https://leetcode.com/problems/sum-of-two-integers/', "difficulty": 'Medium'},
        {"title": 'Reverse Integer', "leetcode_url": 'https://leetcode.com/problems/reverse-integer/', "difficulty": 'Medium'},
    ],
}
